---
instances:
  - name: elasticsearch
    dns:
      - elasticsearch
      - localhost
  - name: kibana
    dns:
      - kibana
      - localhost
  - name: nginx
    dns:
      - nginx
      - localhost