---
name: Deployment

on:
  push:
    branches-ignore: [gh-pages]

jobs:

  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16.2
      - name: Build Dynamicbeat
        run: cd dynamicbeat && make dynamicbeat
      - name: Start dev deployment
        run: docker-compose up -d
      - name: Set up Scorestack
        run: ./dynamicbeat/dynamicbeat --config dynamicbeat/dynamicbeat.ci.yml setup
      - name: Add example checks
        run: ./dynamicbeat/dynamicbeat --config dynamicbeat/dynamicbeat.ci.yml setup checks ./examples
      - name: Run one round
        run: ./dynamicbeat/dynamicbeat --config dynamicbeat/dynamicbeat.ci.yml run --rounds 1

  prod-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16.2
      - name: Build Dynamicbeat
        run: cd dynamicbeat && make dynamicbeat
      - name: Build production images
        run: make build-image
      - name: Start prod deployment
        run: docker-compose -f docker/docker-compose.production.yml up -d
      - name: Set up Scorestack
        run: ./dynamicbeat/dynamicbeat --config dynamicbeat/dynamicbeat.ci.yml setup
      - name: Add example checks
        run: ./dynamicbeat/dynamicbeat --config dynamicbeat/dynamicbeat.ci.yml setup checks ./examples
      - name: Run one round
        run: ./dynamicbeat/dynamicbeat --config dynamicbeat/dynamicbeat.ci.yml run --rounds 1