---
name: GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.2"
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest
      - name: Generate Dynamicbeat command docs
        working-directory: ./dynamicbeat
        run: |
          go get
          go run ./docs/gen.go
      - name: Build book website
        run: mdbook build
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          cname: docs.scorestack.io
